### ISSUE TITLE
Dense feature learning

### ISSUE THREAD

**Issue by sdpscnc** [jspenmar/DeFeat-Net#2]
Hello, thank you for your excellent work. I use the FeatNet network to learn dense features, but I cannot get a feature map with structural information like the PCA processing in your paper. The network outputs H×W×32-dimensional feature maps, which are processed by PCA into H×W×3 and displayed in RGB. Can you give your suggestions? Thank you again.
![feature](https://user-images.githubusercontent.com/20380000/96726625-bc722300-13e4-11eb-8a62-7470c18f6cd0.png)
![rgb](https://user-images.githubusercontent.com/20380000/96726641-c09e4080-13e4-11eb-8bc7-55cbab149216.png)

**Comment by jspenmar** [comment]
Hi, thanks for your interest! As far as I can tell, those feature visualizations look okay. Please remember that these visualizations aren't entirely representative of the learnt features (since we are throwing away a lot of information), and should jut be viewed as a qualitative evaluation. 
Thank you

**Comment by sdpscnc** [comment]
Okay thanks for your suggestions.
